language: r

# Don't fail just for warnings (though these need to be fixed for CRAN)
warnings_are_errors: false

sudo: required

r_check_args: --no-examples

notifications:
  email: false

r_github_packages:
  - jimhester/covr
  - aiorazabala/qmethod

after_success:
  - Rscript -e 'library(covr);codecov()'
